### ISSUE TITLE
Fix pubchem namespace

### ISSUE THREAD

**Issue by cthoyt** [seffnet/seffnet#11]
Everywhere you're mentioning `pubchem` you should really be using `pubchem.compound`

**Comment by AldisiRana** [comment]
@cthoyt I'm not sure I understand what you mean.
The namespace is called 'pubchem.compound'? In the graphs its just called 'pubchem', though.

**Comment by cthoyt** [comment]
Yes, so in the graphs it should be called pubchem.compound

**Comment by AldisiRana** [comment]
Ok. I can do that. 
But it will take an extra step in the SIDER graph since bio2bel creates it as 'pubchem' not 'pubchem.compound'. I'll have to go over all the nodes and change their namespace, unless you're going to change it in bio2bel as well?

**Comment by cthoyt** [comment]
Cray, solved with https://github.com/bio2bel/sider/commit/d1aceaaf5b231197e3a7052ef45d44f7998f1230. Thanks for making me aware.
