### ISSUE TITLE
Use CURIEs instead of node identifiers

### ISSUE THREAD

**Issue by cthoyt** [seffnet/seffnet#16]
You spent a lot of effort to assign numeric identifiers to each node (which we then treat as strings)... would it be possible to skip all of that and just use the CURIEs directly? Or somewhere do these numbers correspond to the indexes in some matrices?

**Comment by AldisiRana** [comment]
Yes, I already tried in the beginning to use the namespace identifiers instead of numbers but there were errors during training the model (I think I tried it with deepwalk)
