### ISSUE TITLE
Deal with duplicate pubchem compounds

### ISSUE THREAD

**Issue by AldisiRana** [seffnet/seffnet#17]
example: 
https://pubchem.ncbi.nlm.nih.gov/compound/2462
https://pubchem.ncbi.nlm.nih.gov/compound/5281004
https://pubchem.ncbi.nlm.nih.gov/compound/Budesonide

These are three different pubchem ID for the same compound.
SIDER graph and DrugBank graph have the same compound with different pubchem IDs, so when merging the two graphs, the compound is saved as two different nodes

**Comment by cthoyt** [comment]
Looks like these entries in PubChem represent different levels of stereospecificity.

**Comment by cthoyt** [comment]
One thing you can do is use InChi keys and throw away the stereochemistry layers to check equivalence
