### ISSUE TITLE
Add weight to edges from DrugBank

### ISSUE THREAD

**Issue by cthoyt** [seffnet/seffnet#25]
Check if DrugBank sucks in nominal IC50 or Ki values. If so, we're done. Otherwise:

- [x] Map drugs to ChEMBL identifiers
- [x] Map drugs' targets to ChEBML identifiers
- [x] Look up pCHEMBL values for drug-target interactions using the [ChEMBL python package](https://github.com/chembl/chembl_webresource_client)
- [x] Generate new edge list using that as the weighting

**Comment by AldisiRana** [comment]
@cthoyt here is something we didn't think about. pchembl values are basically 0 or more. But side effect frequencies are between 0 and 1 (or 0 and 100%). Same with chemical similarities. This will give chemical-target edges higher weights than other edges in the fullgraph.

**Comment by cthoyt** [comment]
Classic machine learning! Time to do some feature normalization. Some options are:

- pchembl values follow a normal distribution (I think) so you can z-score them then transform with the error function (inverse normal distribution function) to get values from [0, 1]
- min/max normalization (maintains distribution but squashes to [0, 1]
- rank normalization

**Comment by AldisiRana** [comment]
instead of an edgelist, I create a pickle file, which will be later used to create the complete weighted graph, and we can create the weighted edgelist from that graph
