### ISSUE TITLE
Seed shouldn't be set during optimization

### ISSUE THREAD

**Issue by cthoyt** [seffnet/seffnet#7]
I'm worried the evaluation won't be fair if they're all doing prediction using the same random seed. I think what you should do is generate a random seed (between 1 and a billion, or whatever) yourself and store that as a user attribute for each run to promote reproducibility.

https://github.com/AldisiRana/SE_KGE/blob/6e7eca5474bae3e7997616c856e13b87e560174e/src/se_kge/optimization.py#L17

https://github.com/AldisiRana/SE_KGE/blob/6e7eca5474bae3e7997616c856e13b87e560174e/src/se_kge/optimization.py#L48

https://github.com/AldisiRana/SE_KGE/blob/6e7eca5474bae3e7997616c856e13b87e560174e/src/se_kge/optimization.py#L83

https://github.com/AldisiRana/SE_KGE/blob/6e7eca5474bae3e7997616c856e13b87e560174e/src/se_kge/optimization.py#L112

https://github.com/AldisiRana/SE_KGE/blob/6e7eca5474bae3e7997616c856e13b87e560174e/src/se_kge/optimization.py#L139

https://github.com/AldisiRana/SE_KGE/blob/6e7eca5474bae3e7997616c856e13b87e560174e/src/se_kge/optimization.py#L168

**Comment by AldisiRana** [comment]
@cthoyt Done
